/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class software_blob_audio_effects_SBSMSEffect */

#ifndef _Included_software_blob_audio_effects_sbsms_SBSMSEffect
#define _Included_software_blob_audio_effects_sbsms_SBSMSEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     software_blob_audio_effects_sbsms_SBSMSEffect
 * Method:    process
 * Signature: ([[DDDDD)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_software_blob_audio_effects_sbsms_SBSMSEffect_process___3_3DDDDD
  (JNIEnv *, jclass, jobjectArray, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     software_blob_audio_effects_sbsms_SBSMSEffect
 * Method:    process
 * Signature: ([[DDD[F)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_software_blob_audio_effects_sbsms_SBSMSEffect_process___3_3DDD_3F
  (JNIEnv *, jclass, jobjectArray, jdouble, jdouble, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
